// starter-trees.js — SCAFFOLDS, not finished reflections.
// These are starting *shapes* for mapping your own paths to failure. They are
// meant to be overwritten: keep the skeleton, replace the branches with the
// ways YOU actually fail. See docs/new-plan.md, Phase B.
// Each is valid wisdom_tree DSL: one root, exactly one `* ` star (tonight's
// minimum ends there), every path ends in `done`. Consume via setDslText(dsl).

const STARTER_TREES = [
  {
    id: "avoidance-map",
    title: "The avoidance map",
    blurb: "Name what you dodged today and the fear underneath it. Replace these branches with your own.",
    dsl: [
      "what did you avoid today?",
      "  what was the avoidance really about?",
      "",
      "what was the avoidance really about?",
      "  fear it wouldn't work > what would you attempt if no one could see it fail?",
      "  the task felt too big > what is the smallest piece you could not fail at?",
      "  genuinely no time > was it time, or fear wearing a time costume?",
      "",
      "* what is one move you'll make tomorrow?",
      "  done",
      "",
      "what would you attempt if no one could see it fail?",
      "  what is one move you'll make tomorrow?",
      "",
      "what is the smallest piece you could not fail at?",
      "  what is one move you'll make tomorrow?",
      "",
      "was it time, or fear wearing a time costume?",
      "  what is one move you'll make tomorrow?",
    ].join("\n"),
  },
  {
    id: "decision-premortem",
    title: "Decision pre-mortem",
    blurb: "Assume the choice already failed, then work backward. The original wisdom-tree move.",
    dsl: [
      "what decision are you sitting with?",
      "  imagine it's a year later and it failed — what went wrong?",
      "",
      "imagine it's a year later and it failed — what went wrong?",
      "  i moved too slow > what would moving fast have actually cost you?",
      "  i moved too fast > what did you skip that you knew mattered?",
      "  it was outside my control > what part was actually inside your control?",
      "",
      "* knowing that, what's the one bet worth making?",
      "  done",
      "",
      "what would moving fast have actually cost you?",
      "  knowing that, what's the one bet worth making?",
      "",
      "what did you skip that you knew mattered?",
      "  knowing that, what's the one bet worth making?",
      "",
      "what part was actually inside your control?",
      "  knowing that, what's the one bet worth making?",
    ].join("\n"),
  },
  {
    id: "energy-audit",
    title: "Energy audit",
    blurb: "Find the pattern under what drains and feeds you, then protect one thing.",
    dsl: [
      "what drained you today?",
      "  what fed you today?",
      "",
      "what fed you today?",
      "  what's the pattern underneath both?",
      "",
      "what's the pattern underneath both?",
      "  a person or place > what boundary would protect your energy?",
      "  a kind of task > what could you stop, delegate, or batch?",
      "  your own expectations > which expectation could you drop?",
      "",
      "* what's one thing you'll protect tomorrow?",
      "  done",
      "",
      "what boundary would protect your energy?",
      "  what's one thing you'll protect tomorrow?",
      "",
      "what could you stop, delegate, or batch?",
      "  what's one thing you'll protect tomorrow?",
      "",
      "which expectation could you drop?",
      "  what's one thing you'll protect tomorrow?",
    ].join("\n"),
  },
  {
    id: "end-of-day",
    title: "End of day, honestly",
    blurb: "The shortest nightly minimum. Demonstrates recall (revisiting what keeps making days hard).",
    dsl: [
      "how did today actually go?",
      "  better than expected > what worked that you want to keep?",
      "  about as expected > what's one thing you'd do differently?",
      "  worse than expected > what made it hard?",
      "",
      "* what's the one thing that matters most tomorrow?",
      "  done",
      "",
      "what worked that you want to keep?",
      "  what's the one thing that matters most tomorrow?",
      "",
      "what's one thing you'd do differently?",
      "  what's the one thing that matters most tomorrow?",
      "",
      "what made it hard?",
      "  recall what made it hard?",
      "  what's the one thing that matters most tomorrow?",
    ].join("\n"),
  },
];

if (typeof module !== "undefined" && module.exports) module.exports = STARTER_TREES;
if (typeof window !== "undefined") window.STARTER_TREES = STARTER_TREES;
